version: '3.8'

services:
  iot:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: trashbin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: